/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preserve that ability, always export from Quest to regenerate this file.
 *   To setup element attributes and CSS properties, use the Quest web app
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import { Dialog, Button } from '@mui/material';
import { styled } from '@mui/material/styles';
import Image1Image from 'src/assets/images/DialogSample_Image.png';
import Form1 from 'src/components/Form1/Form1';
import useDialogSample from 'src/components/DialogSample/useDialogSample';

const TypeQuest = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  boxShadow: `0px 4px 6px rgba(3, 0, 161, 0.2)`,
  borderRadius: `8px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  width: '100%',
  height: `684px`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  overflow: `hidden`,
});

const Image1 = styled('div')({
  backgroundImage: `url(${Image1Image})`,
  backgroundPosition: `center`,
  backgroundSize: `cover`,
  backgroundRepeat: `no-repeat`,
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  width: `390px`,
  height: `257px`,
  margin: `0px`,
});

const Contactusframe = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `380px`,
  height: `624px`,
  margin: `0px 0px 0px 22px`,
  overflow: `hidden`,
});

const Form11 = styled(Form1)(({ theme }) => ({
  flex: `1`,
  position: `absolute`,
  left: `33px`,
  top: `23px`,
}));

const Cardframe = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `390px`,
  height: `392px`,
  margin: `0px 0px 0px 22px`,
  overflow: `hidden`,
});

const TextButton = styled('div')({
  borderRadius: `0px`,
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px 40px 30px 28px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  width: `390px`,
  left: `0px`,
  top: `117px`,
});

const LoremIpsumTestToBeSe = styled('div')(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: theme.palette['Text']['Primary'],
  fontStyle: theme.typography['Typography']['Body 1'].fontStyle,
  fontFamily: theme.typography['Typography']['Body 1'].fontFamily,
  fontWeight: theme.typography['Typography']['Body 1'].fontWeight,
  fontSize: theme.typography['Typography']['Body 1'].fontSize,
  letterSpacing: theme.typography['Typography']['Body 1'].letterSpacing,
  lineHeight: theme.typography['Typography']['Body 1'].lineHeight,
  textDecoration: theme.typography['Typography']['Body 1'].textDecoration,
  textTransform: theme.typography['Typography']['Body 1'].textTransform,
  width: `322px`,
  zIndex: `2`,
  margin: `0px`,
}));

const ButtonClicked = styled('div')(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(107, 104, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Heebo`,
  fontWeight: `700`,
  fontSize: `20px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  height: `48px`,
  width: `138px`,
  zIndex: `1`,
  margin: `15px 0px 0px 0px`,
}));

const ButtonContained = styled(Button)({
  zIndex: `0`,
  margin: `15px 0px 0px 0px`,
});

function DialogSample(props) {
  const { data, fns } = useDialogSample();

  return (
    <TypeQuest className={props.className}>
      <Image1></Image1>
      <Dialog open={data.isDialogOpen} onClose={fns.toggleDialog}>
        <Contactusframe>
          <Form11 open={data.isDialogOpen} onClose={fns.toggleDialog} />
        </Contactusframe>
      </Dialog>
      <Cardframe>
        <TextButton>
          <LoremIpsumTestToBeSe>
            {`Lorem ipsum test to be seen and not read for placement only. Lorem ipsum test to be seen.`}
          </LoremIpsumTestToBeSe>
          {false && <ButtonClicked>{`Button Clicked!`}</ButtonClicked>}
          <ButtonContained
            variant="contained"
            size="large"
            color="primary"
            onClick={fns.toggleDialog}
          >
            {' '}
            Press Me{' '}
          </ButtonContained>
        </TextButton>
      </Cardframe>
    </TypeQuest>
  );
}

export default DialogSample;
